### PR TITLE
change getAttribute "size" to "data-res" on html5.js

### PR DESCRIPTION
**Pull request by halionsp**
- Attribute size not allowed on element source at this point
→https://github.com/sampotts/plyr/issues/1172←

### CODE REVIEW

**Comment by sampotts** [comment]
Why not data-size? Also, this way it’s a breaking change as it’s not backwards compatible. I can’t merge this as is unless it waits for v4.0.0

**Comment by halionsp** [comment]
Sorry not merge. The commit https://github.com/sampotts/plyr/commit/a1fea91794ce527ae08d656c7dab7e1cfc28ecc5  does not work. 💀

**Comment by friday** [comment]
> Why not data-size?

Sorry. I encouraged `data-res` in the issue. `size` is ambiguous imo (could just as well mean file size or bit rate).

**Comment by halionsp** [comment]
> Sorry. I encouraged data-res in the issue. size is ambiguous imo (could just as well mean file size or bit rate).

It is right. I think the same.  The name of `data-size` is better. And it would be available for the major version 4.

```
diff --git a/src/js/html5.js b/src/js/html5.js
index fc8da8c..af3cb20 100644
--- a/src/js/html5.js
+++ b/src/js/html5.js
@@ -23,7 +23,7 @@ const html5 = {
         // Get sizes from <source> elements
         return html5.getSources
             .call(this)
-            .map(source => Number(source.getAttribute('size')))
+            .map(source => Number(source.getAttribute('data-size')))
             .filter(Boolean);
     },
 
@@ -42,14 +42,14 @@ const html5 = {
                 const source = sources.find(source => source.getAttribute('src') === player.source);
 
                 // Return size, if match is found
-                return source && Number(source.getAttribute('size'));
+                return source && Number(source.getAttribute('data-size'));
             },
             set(input) {
                 // Get sources
                 const sources = html5.getSources.call(player);
 
                 // Get first match for requested size
-                const source = sources.find(source => Number(source.getAttribute('size')) === input);
+                const source = sources.find(source => Number(source.getAttribute('data-size')) === input);
 
                 // No matching source found
                 if (!source) {

```

**Comment by arankaren** [comment]
> Sorry. I encouraged data-res in the issue. 

I also think that `data-res` is a good idea for the major version 4

```
diff --git a/src/js/html5.js b/src/js/html5.js
index fc8da8c..af3cb20 100644
--- a/src/js/html5.js
+++ b/src/js/html5.js
@@ -23,7 +23,7 @@ const html5 = {
         // Get sizes from <source> elements
         return html5.getSources
             .call(this)
-            .map(source => Number(source.getAttribute('size')))
+            .map(source => Number(source.getAttribute('data-res')))
             .filter(Boolean);
     },
 
@@ -42,14 +42,14 @@ const html5 = {
                 const source = sources.find(source => source.getAttribute('src') === player.source);
 
                 // Return size, if match is found
-                return source && Number(source.getAttribute('size'));
+                return source && Number(source.getAttribute('data-res'));
             },
             set(input) {
                 // Get sources
                 const sources = html5.getSources.call(player);
 
                 // Get first match for requested size
-                const source = sources.find(source => Number(source.getAttribute('size')) === input);
+                const source = sources.find(source => Number(source.getAttribute('data-res')) === input);
 
                 // No matching source found
                 if (!source) {

```

**Pull request closed without merging**
