### PR TITLE
Import plyr.js into utils.js file. This should fix error #775 when tr…

### PR DESCRIPTION
**Pull request by ispal**
…ying to import using npm

### Link to related issue (if applicable)
https://github.com/sampotts/plyr/issues/775

### Sumary of proposed changes
Import Plyr class directly to utils.js file. I tested this with using the beta version 10 on my local setup and directly modifying utils.js file and added `import Plyr from "./plyr"`. I also builded `dist/plyr.js` file in a forked repository and copy pasted the result to my app and it worked.

### Task list

- [ ] Tested on [supported browsers](https://github.com/sampotts/plyr#browser-support)
- [ ] Gulp build completed

### CODE REVIEW

**Comment by sampotts** [comment]
Wouldn't it be better to do something like this?

```javascript
this instanceof window.Plyr ? this : null
```

**Comment by ispal** [comment]
Then I will get the following error `Uncaught TypeError: Right-hand side of 'instanceof' is not an object`.

Then it should be
`window.Plyr && this instanceof window.Plyr`

Checking if the Plyr exists in the window before checking the instance.

**Comment by sampotts** [comment]
Ah, just realised I should have just used the helper at the top of the file `utils.is.plyr(this) ? this : null`

**Comment by ispal** [comment]
Would love to see fix for this in the next beta because it's kind of blocking me currently.

**Comment by sampotts** [comment]
Can you try v3.0.0-beta.11 ? I just pushed with a change to use `utils.is.plyr()` instead as it follows the standard to use the `is` helper.

**Comment by ispal** [comment]
I tried v3.0.0-beta.11 and that fixed it. Thanks! 👍

**Comment by sampotts** [comment]
Awesome. Thanks for your help with it 👍

**Pull request closed without merging**
