### PR TITLE
Support Youtube NoCookie mode

### PR DESCRIPTION
**Pull request by omarkhatibco**
### Link to related issue (if applicable)
https://github.com/sampotts/plyr/issues/1031
https://github.com/sampotts/plyr/issues/1066

### Summary of proposed changes
According to my local test it's working.

maybe you can make a full test.

### Checklist
- [ ] Use `develop` as the base branch
- [x] Exclude the gulp build (`/dist` changes) from the PR
- [x] Test on [supported browsers](https://github.com/sampotts/plyr#browser-support)

### CODE REVIEW

**Comment by omarkhatibco** [comment]
@friday 
can you test it please ?

**Comment by friday** [comment]
As mentioned in #1066, the URL to the iframe is what matters, and it's generated by the JS SDK. Changing the link to the JS SDK has no effect. You still get the normal youtube URL.

You should be able to see that yourself with your browser dev tools. The YouTube iframe link and the requests are the same right?

**Comment by omarkhatibco** [comment]
@friday 
Here is a screenshort before and after 
**Before**
screenshot 2018-12-13 at 17 51 29

screenshot 2018-12-13 at 17 51 07

**After**

screenshot 2018-12-13 at 17 50 03

screenshot 2018-12-13 at 17 50 21

**Comment by friday** [comment]
Looks good then! I only shimmed the diffs, and thought this was doing something else. The host parameter is new to me (also undocumented it seems).

I'm going to leave this for @sampotts to test and review. I don't even have the plyr repo on my computer any more.

Also: Please make PR's to the `develop` branch in the future.

**Comment by CODECRATER** [comment]
Did this ever make it into a formal release? I'm having a little bit of difficulty making noCookie mode work as intended.

**Comment by omarkhatibco** [comment]
@CODECRATER , 

it's live since 2018, you could use it directly.

**Comment by CODECRATER** [comment]
> @CODECRATER ,
> 
> it's live since 2018, you could use it directly.

Omar,

Thanks for the quick reply.

I'm trying to enable noCookie mode to be GDPR compliant and it's half working because the embed URL changes to "https://www.youtube-nocookie.com/embed/". However, my Chrome browser is still displaying cookies from YouTube.com when I use a new Incognito window.


Here is my Plyr YouTube JS code:

`	// Video Player
	const player = new Plyr('.fps-video-player', {
		youtube: {
			noCookie: true,
		},
		controls: [
			"play-large",
			"play",
			"progress",
			"current-time",
			"mute",
			"volume",
			"fullscreen"
		]
	});`


Here is my Plyr YouTube HTML code:

`<div class="fps-video-player" data-plyr-provider="youtube" data-plyr-embed-id="fQqkxwuBLcU"></div>`


Can you please give me an example of working YouTube/Plyr NoCookie embed code?

Thank you so much.

**Comment by omarkhatibco** [comment]
@CODECRATER , 

check the url in the iframe, it should be youtube-nocookie. 

if it is so, then your are safe even if there is a cookies from yoututbe.

**Pull request merged**
