### PR TITLE
feat: add markers

### PR DESCRIPTION
**Pull request by ForeverSc**
### Link to related issue (if applicable)
#278 

### Summary of proposed changes
add markers option to custom some markers on the progress bar 
```
...
markers: {
  enabled: true,
  points: [
    {
      time: 10, // marker point time
      tip: 'first marker', // marker point hover display tip
    },
    {
      time: 20,
      tipHTML: '<strong>second</strong> marker', // or you can custom marker hover tip by innerHTML
    }
  ]
}
...
```
image

### CODE REVIEW

**Review by benutzer-prog — APPROVED** [review]

**Review by benutzer-prog — APPROVED** [review]

**Comment by adeeb1** [comment]
Love this feature! For those interested, I've merged it into my fork with a few additional changes. Here's the PR: https://github.com/ClassHook/plyr/pull/8

@ForeverSc feel free to include some of those changes in this PR if you think they're relevant. I'd also be happy to create a separate PR if it's easier.

**Comment by lofcz** [comment]
@sampotts can we get this merged?

**Review by sampotts — APPROVED** [review]

**Comment by sampotts** [comment]
Thanks! I'll write up some docs and get this published!

**Comment by evansque** [comment]
This is awesome, thanks @sampotts I've been really waiting for this release

**Comment by sampotts** [comment]
Thanks, @evansque. The current Plyr UI design doesn't really adapt well to chapter/marker support but it's definitely something we'll consider for the Vidstack UI.

**Comment by mixalistzikas** [comment]
@sampotts Hello, I just (also) took 3.7.0 version, but doesn't work. 

Is there something wrong with this code?

`var defaultOptions = {
            captions: {
                active: true,
                update: true,
                language: 'en'
            },
            markers: { enabled: true, points: [{ time: 20, label: 'Label 1' }] }
        };`

new Plyr(video, defaultOptions);

**Pull request merged**
