### PR TITLE
Update link to working dash.js demo (was broken)

### PR DESCRIPTION
**Pull request by jonathanarbely**
### Checklist
- [x] Use `develop` as the base branch
- [x] Exclude the gulp build (`/dist` changes) from the PR
- [x] Test on [supported browsers](https://github.com/sampotts/plyr#browser-support)

### CODE REVIEW

**Review by sampotts — APPROVED** [review]
Great, thanks!

**Review by sampotts — CHANGES_REQUESTED** [review]
Actually, should this not be a template like before?

**Comment by jonathanarbely** [comment]
> Actually, should this not be a template like before?

What exactly do you mean? I'll be happy to fix it.

**Review by sampotts — APPROVED** [review]

**Comment by sampotts** [comment]
> > Actually, should this not be a template like before?
> 
> What exactly do you mean? I'll be happy to fix it.

All good. I updated it. Thanks 👍

**Pull request merged**
