### PR TITLE
Added react port

### PR DESCRIPTION
**Pull request by xDae**
### Sumary of proposed changes
Added the react port of Plyr in the Readme file

### Task list

- [x] Tested on [supported browsers](https://github.com/sampotts/plyr#browser-support)
- [x] Gulp build completed

### CODE REVIEW

**Comment by sampotts** [comment]
Awesome. Will you be able to update this when v3 is done? Currently in the `develop` branch but it's using ES6 etc.

**Comment by xDae** [comment]
yeah! I use to keep the library updated 👍

**Comment by xDae** [comment]
what happened with this PR?

**Comment by sampotts** [comment]
Sorry, merged.

**Comment by xDae** [comment]
thanks @sampotts 👍

**Pull request merged**
