### PR TITLE
Label/tooltip fix

### PR DESCRIPTION
**Pull request by russitto**
### Sumary of proposed changes 
- fast forward and rewind **labels fix**
- yarn installer supported
- no exec perms @ svg files

### CODE REVIEW

**Comment by SamPotts** [comment]
Cheers for this - I'm still working on the JS so don't worry too much about working on that. 

What's Yarn? NPM-like thing?

**Comment by steelywing** [comment]
yarn is `npm` alternative and faster, the `yarn.lock` file should be `.gitignore`

**Comment by SamPotts** [comment]
OK I'll check it out - cheers! 👍

**Comment by russitto** [comment]
Hi.
dont ignore yarn.lock file.
because:
https://github.com/yarnpkg/yarn/issues/1583
👋😁

**Comment by SamPotts** [comment]
I'd probably rather keep skins seperate if possible. I have enough to maintain as it is...

**Comment by russitto** [comment]
Last commits are not for mege ;-)

**Comment by SamPotts** [comment]
Ah ok I'll manually merge the rest.

**Comment by sampotts** [comment]
Closing this one for now

**Pull request closed without merging**
