### PR TITLE
Speed improvements

### PR DESCRIPTION
**Pull request by friday**
Relates to #1002, but also changes some other things.

I think I need some feedback on it since it seems to go against the intention behind the original API design.

Changes:
* `ui.setSpeedMenu()` was renamed `ui.updateSpeedMenu()` and now only updates the menu. Previously it also took an optional array and used it to set `this.options.speed` unless the provider was YouTube. But this option was only used from the Vimeo plugin for clearing the menu if `setPlaybackRate` failed. Instead the default `[0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]` was used, and the config options was used to filter this array. So anything in the config which was not in this array was filtered out (also preventing #1002).
* `this.options.speed` is now set separately per provider. HTML5 uses the config directly. Vimeo uses the config, but filters out values it can't handle (under `0.5` or over `2.0`). YouTube ignores the config in favor of their own `instance.getAvailablePlaybackRates()`. Since the user config could be `[0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5]` for example, filtering two arrays against each other could end up losing most or even all options. I think we have to improve our API (min/max rather than options), or even UI (slider perhaps?) to make sense of this.
* The `speed` setter now *only* uses the input. Previously it would fallback to the localStorage or config if you set it to a non-number. and also use min/max to contain the value between 0.1 and 2. I don't think this made sense. Now it instead gets the `closest` supported value from `this.options.speed`, so if you try to set it to `1.6` but this isn't supported you get the closest alternative ex `1.5`.
* Since the speed setter no longer "resets" if you pass a non-number. I had to change this in ui:

```js
this.speed = null;
```

to:

```js
this.speed = this.storage.get('speed') || this.config.speed.selected;
```

I don't think this is the right place for it though? I also needed a `setTimeout` to make this work, which felt like a hack. So pointers would be welcome.

### CODE REVIEW

**Comment by Astray-git** [comment]
Can we have an option for whether to save speed in storage?

**Comment by sampotts** [comment]
> Can we have an option for whether to save speed in storage? 

Do you mean rather than disabling storage completely? I guess we could get more granular with it, yep.

**Comment by friday** [comment]
I think that's a good separate suggestion.

Storage could be both an object or boolean, where `true` is translated to `{volume: true, muted: true, quality: true, speed: true, captions: true, language: true}` (and `false` to the opposite obviously).

**Comment by sampotts** [comment]
@friday I agree with the change to the setter. Should we make this consist with the others though like quality, volume, muted, speed? They all seem to have similar behaviour (fall back to storage or config).

**Comment by friday** [comment]
> Should we make this consist with the others though like quality, volume, muted, speed? They all seem to have similar behaviour (fall back to storage or config).

Yeah, I do think so. Setters shouldn't have fallbacks imo.

**Comment by jmprovencher** [comment]
Any update on this ? Will it be merged?

**Comment by spmeesseman** [comment]
i added to an issue that asked for more speed steps but just saw this, beautiful. will this be merged into main branch the future?

**Comment by sampotts** [comment]
Closing this as I've cherry picked parts of it but left the setters logic for now. That probably needs a rework for all setters at the same time. Probably a `v4` thing.

**Pull request closed without merging**
