### PR TITLE
removes unnecessary height

### PR DESCRIPTION
**Pull request by brunoamaral**
### Link to related issue (if applicable)
https://github.com/sampotts/plyr/issues/1723

### Summary of proposed changes

The height setting doesn't work well with Bootstrap, removing it fixes the problem.

### Checklist
- [ ] Use `develop` as the base branch
- [ ] Exclude the gulp build (`/dist` changes) from the PR
- [x] Test on [supported browsers](https://github.com/sampotts/plyr#browser-support)

### CODE REVIEW

**Comment by skerbis** [comment]
same for UiKit

**Comment by sampotts** [comment]
Will merge this one manually.

**Comment by brunoamaral** [comment]
My pleasure, @sampotts ! 🙇

**Comment by shravan2x** [comment]
@brunoamaral @skerbis I'm the person who initially added the `height: 100%` in the linked PR above. Without it, Plyr does not resize responsively.

When using with Bootstrap or UIKit, could you try wrapping the Plyr container in a div?

**Comment by brunoamaral** [comment]
Hi @shravan2x , here's the code I am using right now, with the updated version of ply:

```html
<div class="plyr__video-embed player">
<iframe src="https://www.youtube.com/embed/rHKwIYsPXLg?origin=https://plyr.io&iv_load_policy=3&modestbranding=1&playsinline=1&showinfo=0&rel=0&enablejsapi=1" 
allowfullscreen allowtransparency=true allow=autoplay loading=lazy>
</iframe>
</div>
```

The result is in this link: https://brunoamaral.eu/post/algorithms-artificial-intelligence-and-us/ 

It seems to work well, is your suggestion to add another div around that?

**Pull request closed without merging**
