### PR TITLE
Fix fast-forward control

### PR DESCRIPTION
**Pull request by saadshahd**
fast-forward control doesn't work.

### Sumary of proposed changes
`controls.createButton` expects `forward` key not `fast-forward` https://github.com/sampotts/plyr/blob/bb7eea27e513bf33dd4a4d846b3234b37a5be48d/src/js/defaults.js#L286

### Task list

- [x] Tested on [supported browsers](https://github.com/sampotts/plyr#browser-support)
- [x] Gulp build completed

### CODE REVIEW

**Comment by sampotts** [comment]
I think `fast-forward` makes more sense doesn't it?

**Comment by saadshahd** [comment]
@sampotts Yes I believe so too, for sake of consistency. I'll do it.

**Comment by saadshahd** [comment]
@sampotts I tried to unify its name to be `fastForward` but doing so will introduce breaking changes to the module exported API.

**Comment by sampotts** [comment]
I just meant the controls side of things.

**Comment by saadshahd** [comment]
I updated the controls side only @sampotts

**Comment by saadshahd** [comment]
and you could check the whole API changes from here https://github.com/sampotts/plyr/compare/master...saadshahd:fix/unify-fast-forward-naming?expand=1

**Comment by sampotts** [comment]
Cheers 👍

**Pull request merged**
