### PR TITLE
Preview seek/scrubbing thumbnails

### PR DESCRIPTION
**Pull request by jamesoflol**
### Link to related issue (if applicable)
https://github.com/sampotts/plyr/issues/46
https://github.com/sampotts/plyr/pull/376
https://github.com/sampotts/plyr/issues/1159

### Summary of proposed changes
When user hovers seek bar, they see a preview image
When they drag the seek bar (scrubbing) they see a larger preview image

### Checklist
- [x ] Use `develop` as the base branch
- [x ] Exclude the gulp build (`/dist` changes) from the PR
- [x ] Test on [supported browsers](https://github.com/sampotts/plyr#browser-support)

### Demo:
https://s3-ap-southeast-2.amazonaws.com/jameslol-test/plyr-preview-thumbs/demo/index.html

### Notes:

 * Settings:
    previewThumbnails: {
        enabled: true,
        src: [
          'https://dev.videohop.com.au/s3/v/bluemoon/100p/100p.vtt',
          'https://dev.videohop.com.au/s3/v/bluemoon/240p/240p.vtt',
        ]
    }
 * Allows multiple qualities
   - Each VTT file MUST share the same interval/timings. it would cause silliness to have different timings. and the current logic for progressing up through qualities relies on each quality having the same index
   - While hovering the same time, both small thumb and fullsize will progressively load higher qualities in order until the image's naturalHeight is greater than or equal to the contain height. (or of course, until we hit the largest that we have)
 * I'd recommend increasing the height of the seek bar - it's currently a bit thin for easily keeping the preview showing. Something like
.plyr__progress input[type=range] {
    padding-top: 15px;
    padding-bottom: 15px;
}
 * Thumbs are set via JS settings on Plyr init, not HTML5 'track' property. Using the track property would be a bit gross, because it doesn't support custom 'kinds'. kind=metadata might be used for something else, and we want to allow multiple thumbnails tracks. Tracks must have a unique combination of 'kind' and 'label'. We would have to do something like kind=metadata,label=thumbnails1 / kind=metadata,label=thumbnails2. Square peg, round hole
 * It currently works fantastically with jpeg sprites. If you use individual images instead, ymmv. There's no perfect solution to using individual images, and it has many downsides.

### Todo:
- Add to readme
  - Include notes/specs on jpeg sprites

### Todo later:
- See if the vtt parser function accepts comments https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
  - Also, hours is optional? (can be omitted instead of writing '00:')

### CODE REVIEW

**Comment by jamesoflol** [comment]
Have updated the code to use jpeg sprites, and have generated jpeg sprites for the blue moon demo video, and updated my demo page accordingly. It is much snappier now.

**Comment by jamesoflol** [comment]
- Fixed bug: Edge seek errors: Replaced array spread with Array.from()
- Fixed IE11 bug: seek time was offset to the left. Required an extra container div to facilitate this

**Comment by sampotts** [comment]
Thanks! I'll give this a go locally

**Comment by sampotts** [comment]
Looks great! I've shot you a message on Slack about getting the images you've created and the VTT so I can add them to the demo. I'll use some of those notes you've written for the docs.

**Comment by regiside** [comment]
This is such a great feature! Thank you so much James for this top notch implementation, it really takes Plyr to the next level. I just finished implementing a feature that automatically generates the sprite sheets and VTTs from vimeo videos on our site using a CLI tool called Movie Thumbnailer (mtn) and PHP, and I'd like to make a video explaining how to put it all together. I'm wondering though if there's any way to adjust the size that the thumbnails get rendered at. Right now it seems like the box is about 200px wide and I'd like something a little smaller like 160px. Thanks!  

-Reggie

**Pull request merged**
